### ISSUE TITLE
Docker Compose テンプレ

### ISSUE THREAD

**Issue by Tobotobo** [Tobotobo/my_knowledge_base#45]
混ぜこぜなので、欲しいところを適当に切り取って使うこと
```yaml
services:
  nginx:
    image: nginx:latest
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
      args:
        VARIANT: ${ALMALINUX_VARIANT}
    user: ${USER_UID}:${USER_GID}
    ports:
      - "80:80"
      - "${GITEA_SSH_PORT:-2222}:22"
    depends_on:
      - gitea
    networks:
      - gitea_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
    tty: true

volumes:
  gitea_data:
  gitea_db_data:
  gitea_act_runner_data:

networks:
  gitea_network:
    external: false
```
